## Read full CSV

In [52]:
import pandas as pd
%pip install music21
from music21 import *
#¡Atencion! Aquí tu path a una carpeta en la que este un archivo MuseScore3.exe
#yo copie el archivo MuseScore3.exe de la carpeta de instalacion a la carpeta en la que tengo el repositorio
path_to_musescore = 'C:/Users/ifc04/OneDrive/Desktop/UNIVERSIDAD/Audio and Music Processing Lab/Lab 3 - Ethnomusicology/GMD-classification/data/'
environment.set('musescoreDirectPNGPath', path_to_musescore)

Requirement already satisfied: music21 in c:\users\ifc04\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (8.1.0)
Requirement already satisfied: jsonpickle in c:\users\ifc04\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from music21) (2.2.0)
Requirement already satisfied: chardet in c:\users\ifc04\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from music21) (5.1.0)
Requirement already satisfied: webcolors>=1.5 in c:\users\ifc04\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from music21) (1.12)
Requirement already satisfied: numpy in c:\users\ifc04\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from music21) (1.23.4)
Requirement already satisfied: joblib in c:\users\ifc04\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from music21) (1.2.0)
Requirement already satisfied: matplotlib in c:\users\ifc04\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from music21) (3.5.3)
Requirement already satisfied: requests in c:\users\ifc04\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from music21) (2.28.1)
Requirement already satisfied: more-itertools in c:\users\ifc04\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from music21) (9.1.0)
Requirement already satisfied: packaging>=20.0 in c:\users\ifc04\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from matplotlib->music21) (20.9)
Requirement already satisfied: cycler>=0.10 in c:\users\ifc04\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from matplotlib->music21) (0.11.0)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\ifc04\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from matplotlib->music21) (1.4.4)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\ifc04\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from matplotlib->music21) (4.38.0)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\ifc04\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from matplotlib->music21) (2.8.2)
Requirement already satisfied: pyparsing>=2.2.1 in c:\users\ifc04\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from matplotlib->music21) (3.0.9)
Requirement already satisfied: pillow>=6.2.0 in c:\users\ifc04\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from matplotlib->music21) (9.3.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\ifc04\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from requests->music21) (1.26.13)
Requirement already satisfied: idna<4,>=2.5 in c:\users\ifc04\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from requests->music21) (3.4)
Requirement already satisfied: charset-normalizer<3,>=2 in c:\users\ifc04\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from requests->music21) (2.1.1)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\ifc04\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from requests->music21) (2022.12.7)
Requirement already satisfied: six>=1.5 in c:\users\ifc04\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from python-dateutil>=2.7->matplotlib->music21) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 23.0 -> 23.0.1
[notice] To update, run: C:\Users\ifc04\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [53]:

#Read galician_musicxml_full.csv but is in father folder
df = pd.read_csv('../galician_musicxml_full.csv',quotechar='"',skipinitialspace=True)

#df = pd.read_csv('galician_musicxml_full.csv',quotechar='"',skipinitialspace=True)

#drop first column
#name first column id
df = df.rename(columns={'Unnamed: 0': 'id'})
#In this case we dont need the first column because index of row=name of musicxml file
#have in mind that we do need it for the other csv files
df

      id                   name                   location
0      0   Muiñeira dos Fosados                    Fosados
1      1       Detrás das airas                      airas
2      2   Muiñeira de Quindous                   Quindous
3      3   Muiñeira de Quindous  Quindous, Cervantes, Lugo
4      4               Muiñeira                        NaN
..   ...                    ...                        ...
449  449    Carballesa do Incio                      Incio
450  450  Muiñeira de Vilarmide     Vilarmide, A Pontenova
451  451               Na Ruada                        NaN
452  452  Danza Anterga de Lugo                       Lugo
453  453    Carballesa do Incio                      Incio

[454 rows x 3 columns]

## Read file with all the locations

In [54]:

#Read galician_musicxml_full.csv in father folder
df_located = pd.read_csv('../galician_musicxml_located.csv',quotechar='"',skipinitialspace=True)
#df_located = pd.read_csv('galician_musicxml_located.csv',quotechar='"',skipinitialspace=True)
#Rename first column to id
df_located = df_located.rename(columns={df_located.columns[0]: "id"})
"""
Have in mind that for this case the id IS important. ID is the name of the musicxml file
"""
df_located

      id                     name  parroquia     concellu    province
0      1         Detrás das airas        NaN     As Airas     Ourense
1      2     Muiñeira de Quindous   Quindous    Cervantes        Lugo
2      3     Muiñeira de Quindous   Quindous    Cervantes        Lugo
3      5     Muiñeira de Monforte        NaN     Monforte        Lugo
4      6      Muiñeira de Ventosa        NaN      Ventosa  Pontevedra
..   ...                      ...        ...          ...         ...
255  446  Ribeirana de Pontevedra        NaN   Pontevedra  Pontevedra
256  449      Carballesa do Incio        NaN      O Incio        Lugo
257  450    Muiñeira de Vilarmide  Vilarmide  A Pontenova        Lugo
258  452    Danza Anterga de Lugo        NaN         Lugo        Lugo
259  453      Carballesa do Incio        NaN      O Incio        Lugo

[260 rows x 5 columns]

In [55]:
#Example, let's say we want to load a Muiñeira de Quindous
#Show all the rows where the id is equal to "Muiñeira de Quindous"
df_located.loc[df_located['name'] == 'Muiñeira de Quindous']

   id                  name parroquia   concellu province
1   2  Muiñeira de Quindous  Quindous  Cervantes     Lugo
2   3  Muiñeira de Quindous  Quindous  Cervantes     Lugo

In [56]:
def load_musicxml(index):
    """
    Load a musicxml file and return a music21 stream
    """
    #Set musicxml_file as a file in path data/name and name being string of the index and .musicxml
    #musicxml_file = 'data/' + str(index) + '.musicxml'
    musicxml_file =str(index) + '.musicxml'
    #The files are in the folder data
    #Load the musicxml file
    #print(musicxml_file)
    try:
        s = corpus.parse(musicxml_file)

    except Exception as e:
        #Get exception if the file is not found
        s=converter.parse(musicxml_file)
        return s
    return s

#Let's continue with the example, loading hte second muiñeira that appears:
#muiñeira=load_musicxml(3)
s = load_musicxml(1)
s.analyze('key')

#For loop to 453
#Create dataframe with id, name, key
df_key=pd.DataFrame(columns=['id','name','key'])
for i in range(453):
    #get index of df_located
    index=df.loc[i]['id']
    s = load_musicxml(index)
    if s is not None:
        key=s.analyze('key')
        #Get name of the song in df in this case we can use the index because the index of df is the same as the id
        name=df.loc[i]['name']
        df_key.loc[i]=[index,name, key]

df_key_located=pd.DataFrame(columns=['id','name','parroquia','concellu','province','key'])
i=0
for i in range(260):
    #get index of df_located
    index=df_located.loc[i]['id']
    s = load_musicxml(index)
    if s is not None:
        key=s.analyze('key')
        #Get name of the song in df in this case we can use the index because the index of df is the same as the id
        name=df_located.loc[i]['name']
        parroquia=df_located.loc[i]['parroquia']
        concellu=df_located.loc[i]['concellu']
        province=df_located.loc[i]['province']
        df_key_located.loc[i]=[index,name,parroquia,concellu,province, key]

df_key

      id                   name       key
0      0   Muiñeira dos Fosados   b minor
1      1       Detrás das airas   a minor
2      2   Muiñeira de Quindous  B- major
3      3   Muiñeira de Quindous   G major
4      4               Muiñeira   G major
..   ...                    ...       ...
448  448             Carballesa   C major
449  449    Carballesa do Incio   C major
450  450  Muiñeira de Vilarmide   C major
451  451               Na Ruada   C major
452  452  Danza Anterga de Lugo   C major

[453 rows x 3 columns]

In [57]:
df_key.drop(df_key.columns[0], axis=1, inplace=True)

df_key

                      name       key
0     Muiñeira dos Fosados   b minor
1         Detrás das airas   a minor
2     Muiñeira de Quindous  B- major
3     Muiñeira de Quindous   G major
4                 Muiñeira   G major
..                     ...       ...
448             Carballesa   C major
449    Carballesa do Incio   C major
450  Muiñeira de Vilarmide   C major
451               Na Ruada   C major
452  Danza Anterga de Lugo   C major

[453 rows x 2 columns]

In [58]:
df_key_located.drop(df_key_located.columns[0], axis=1, inplace=True)

df_key_located

                        name  parroquia     concellu    province       key
0           Detrás das airas        NaN     As Airas     Ourense   a minor
1       Muiñeira de Quindous   Quindous    Cervantes        Lugo  B- major
2       Muiñeira de Quindous   Quindous    Cervantes        Lugo   G major
3       Muiñeira de Monforte        NaN     Monforte        Lugo   G major
4        Muiñeira de Ventosa        NaN      Ventosa  Pontevedra   F major
..                       ...        ...          ...         ...       ...
255  Ribeirana de Pontevedra        NaN   Pontevedra  Pontevedra   C major
256      Carballesa do Incio        NaN      O Incio        Lugo   C major
257    Muiñeira de Vilarmide  Vilarmide  A Pontenova        Lugo   C major
258    Danza Anterga de Lugo        NaN         Lugo        Lugo   C major
259      Carballesa do Incio        NaN      O Incio        Lugo   C major

[260 rows x 5 columns]

In [62]:
#Both df to csv
#rename first index to id
df_key.to_csv('df_key.csv')
df_key_located.to_csv('df_key_located.csv')